version: '3.5'
services:
  # The Application
  app:
    build:
      context: ./
      dockerfile: ./app.dockerfile
    restart: always
    volumes:
      - ./:/var/www/html:cached
    ports:
      - "80:80"
    environment:
      - "DB_HOST=${DB_HOST}"

  # The Database
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      - "MYSQL_DATABASE=${DB_DATABASE}"
      - "MYSQL_USER=${DB_USERNAME}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    ports:
      - "3306:3306"

volumes:
  dbdata: